export const FETCH_NAMES_SUCCESS = 'FETCH_NAMES_SUCCESS';
export const FAVSCREEN_NAME_FAVORITE = 'FAVSCREEN_NAME_FAVORITE';
export const FAVSCREEN_NAME_UNFAVORITE =
  'FAVSCREEN_NAME_UNFAVORITE';
export const LISTSCREEN_NAME_FAVORITE = 'LISTSCREEN_NAME_FAVORITE';
export const LISTSCREEN_NAME_UNFAVORITE = 'LISTSCREEN_NAME_UNFAVORITE';

export const LISTSCREEN_VIEW = 'LISTSCREEN_VIEW';
export const FAVSCREEN_VIEW = 'FAVSCREEN_VIEW';
