export const FETCH_NAMES_SUCCESS = 'FETCH_NAMES_SUCCESS';

export const LISTSCREEN_VIEW = 'LISTSCREEN_VIEW';
export const FAVSCREEN_VIEW = 'FAVSCREEN_VIEW';

export const LISTSCREEN_SCROLL = 'LISTSCREEN_SCROLL';
export const FAVSCREEN_SCROLL = 'FAVSCREEN_SCROLL';

export const FAVSCREEN_NAME_FAVORITE = 'FAVSCREEN_NAME_FAVORITE';
export const FAVSCREEN_NAME_UNFAVORITE = 'FAVSCREEN_NAME_UNFAVORITE';
export const LISTSCREEN_NAME_FAVORITE = 'LISTSCREEN_NAME_FAVORITE';
export const LISTSCREEN_NAME_UNFAVORITE = 'LISTSCREEN_NAME_UNFAVORITE';

export const LISTSCREEN_NAME_OPEN = 'LISTSCREEN_NAME_OPEN';
export const FAVSCREEN_NAME_OPEN = 'FAVSCREEN_NAME_OPEN';

export const LISTSCREEN_FEMALETAB_PRESS = 'LISTSCREEN_FEMALETAB_PRESS';
export const LISTSCREEN_MALETAB_PRESS = 'LISTSCREEN_MALETAB_PRESS';
export const FAVSCREEN_FEMALETAB_PRESS = 'FAVSCREEN_FEMALETAB_PRESS';
export const FAVSCREEN_MALETAB_PRESS = 'FAVSCREEN_MALETAB_PRESS';
