export const FETCH_NAMES_SUCCESS = 'FETCH_NAMES_SUCCESS';
export const FAVORITESSCREEN_NAME_FAVORITE = 'FAVORITESSCREEN_NAME_FAVORITE';
export const FAVORITESSCREEN_NAME_UNFAVORITE =
  'FAVORITESSCREEN_NAME_UNFAVORITE';
export const LISTSCREEN_NAME_FAVORITE = 'LISTSCREEN_NAME_FAVORITE';
export const LISTSCREEN_NAME_UNFAVORITE = 'LISTSCREEN_NAME_UNFAVORITE';

export const LISTSCREEN_VIEW = 'LISTSCREEN_VIEW';
export const FAVORITESSCREEN_VIEW = 'FAVORITESSCREEN_VIEW';
