export const FETCH_NAMES_REQUEST = 'FETCH_NAMES_REQUEST';
export const FETCH_NAMES_SUCCESS = 'FETCH_NAMES_SUCCESS';

export const LISTSCREEN_VIEW = 'LISTSCREEN_VIEW';
export const FAVSCREEN_VIEW = 'FAVSCREEN_VIEW';

export const LISTSCREEN_SCROLL = 'LISTSCREEN_SCROLL';
export const FAVSCREEN_SCROLL = 'FAVSCREEN_SCROLL';

export const FAVSCREEN_NAME_FAVORITE = 'FAVSCREEN_NAME_FAVORITE';
export const FAVSCREEN_NAME_UNFAVORITE = 'FAVSCREEN_NAME_UNFAVORITE';
export const LISTSCREEN_NAME_FAVORITE = 'LISTSCREEN_NAME_FAVORITE';
export const LISTSCREEN_NAME_UNFAVORITE = 'LISTSCREEN_NAME_UNFAVORITE';

export const LISTSCREEN_NAME_OPEN = 'LISTSCREEN_NAME_OPEN';
export const FAVSCREEN_NAME_OPEN = 'FAVSCREEN_NAME_OPEN';

export const LISTSCREEN_RATEALERT_SHOW = 'LISTSCREEN_RATEALERT_SHOW';
export const LISTSCREEN_RATEALERT_RATE = 'LISTSCREEN_RATEALERT_RATE';
export const LISTSCREEN_RATEALERT_UPDATEVISITS =
  'LISTSCREEN_RATEALERT_UPDATEVISITS';
export const LISTSCREEN_RATEALERT_RESETVISITS =
  'LISTSCREEN_RATEALERT_RESETVISITS';
