# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'babynamespro' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for babynamespro
  pod 'Amplitude-iOS', '~> 4.3.1'

  target 'babynamesproTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
