# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'babynames' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for babynames
  pod 'Amplitude-iOS', '~> 4.3.1'

  target 'babynamesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
